name: matelive
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+41

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.3.8
  http: ^0.13.4
  get_storage: ^2.0.3
  flutter_html: ^2.1.5
  pusher_client: ^2.0.0
  audioplayers: ^0.20.1
  image_picker: ^0.8.4+4
  auto_size_text: ^3.0.0
  pull_to_refresh: ^2.0.0
  in_app_purchase: ^3.0.4
  stop_watch_timer: ^1.3.1
  proximity_sensor: ^1.0.2
  agora_rtc_engine: ^5.2.0
  package_info_plus: ^1.4.2
  permission_handler: ^9.2.0
  google_maps_flutter: ^2.1.1
  font_awesome_flutter: ^10.1.0
  line_awesome_flutter: ^2.0.0
  html_editor_enhanced: ^2.4.0+1
  cached_network_image: ^3.1.0+1
  rotated_corner_decoration: ^2.0.0
  syncfusion_flutter_pdfviewer: ^20.1.55-beta
  flutter_chat_bubble: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/sounds/
    - assets/images/
    - assets/documents/
    - assets/images/welcomePage/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
          weight: 400
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost-SemiBold.ttf
          weight: 600